# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 981, 631))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.line_2 = QtWidgets.QFrame(self.tab_1)
        self.line_2.setGeometry(QtCore.QRect(280, 0, 20, 601))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_1)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 0, 281, 601))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.svgFilePathLabel = QtWidgets.QLabel(self.tab)
        self.svgFilePathLabel.setGeometry(QtCore.QRect(120, 10, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.svgFilePathLabel.setFont(font)
        self.svgFilePathLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.svgFilePathLabel.setObjectName("svgFilePathLabel")
        self.svgImportButton = QtWidgets.QPushButton(self.tab)
        self.svgImportButton.setGeometry(QtCore.QRect(10, 10, 113, 41))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("GUI/icons//navigation/png/upload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.svgImportButton.setIcon(icon)
        self.svgImportButton.setObjectName("svgImportButton")
        self.svgExportButton = QtWidgets.QPushButton(self.tab)
        self.svgExportButton.setGeometry(QtCore.QRect(30, 530, 191, 41))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("GUI/icons//navigation/png/download.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.svgExportButton.setIcon(icon1)
        self.svgExportButton.setObjectName("svgExportButton")
        self.generateSvgToolpath = QtWidgets.QPushButton(self.tab)
        self.generateSvgToolpath.setGeometry(QtCore.QRect(30, 460, 191, 41))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("GUI/icons//navigation/png/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.generateSvgToolpath.setIcon(icon2)
        self.generateSvgToolpath.setObjectName("generateSvgToolpath")
        self.xPosLabel_3 = QtWidgets.QLabel(self.tab)
        self.xPosLabel_3.setGeometry(QtCore.QRect(142, 216, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.xPosLabel_3.setFont(font)
        self.xPosLabel_3.setStyleSheet("")
        self.xPosLabel_3.setObjectName("xPosLabel_3")
        self.xPosLabel_5 = QtWidgets.QLabel(self.tab)
        self.xPosLabel_5.setGeometry(QtCore.QRect(12, 275, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.xPosLabel_5.setFont(font)
        self.xPosLabel_5.setStyleSheet("")
        self.xPosLabel_5.setObjectName("xPosLabel_5")
        self.depth = QtWidgets.QDoubleSpinBox(self.tab)
        self.depth.setGeometry(QtCore.QRect(10, 296, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.depth.setFont(font)
        self.depth.setStyleSheet("")
        self.depth.setDecimals(2)
        self.depth.setMinimum(0.0)
        self.depth.setMaximum(100.0)
        self.depth.setSingleStep(1.0)
        self.depth.setObjectName("depth")
        self.numberOfLayers = QtWidgets.QDoubleSpinBox(self.tab)
        self.numberOfLayers.setGeometry(QtCore.QRect(140, 296, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.numberOfLayers.setFont(font)
        self.numberOfLayers.setStyleSheet("")
        self.numberOfLayers.setDecimals(0)
        self.numberOfLayers.setMinimum(1.0)
        self.numberOfLayers.setMaximum(100.0)
        self.numberOfLayers.setSingleStep(1.0)
        self.numberOfLayers.setObjectName("numberOfLayers")
        self.safetyDistance = QtWidgets.QDoubleSpinBox(self.tab)
        self.safetyDistance.setGeometry(QtCore.QRect(140, 237, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.safetyDistance.setFont(font)
        self.safetyDistance.setStyleSheet("")
        self.safetyDistance.setDecimals(1)
        self.safetyDistance.setMinimum(0.0)
        self.safetyDistance.setMaximum(400.0)
        self.safetyDistance.setSingleStep(0.1)
        self.safetyDistance.setProperty("value", 5.0)
        self.safetyDistance.setObjectName("safetyDistance")
        self.xPosLabel_2 = QtWidgets.QLabel(self.tab)
        self.xPosLabel_2.setGeometry(QtCore.QRect(12, 216, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.xPosLabel_2.setFont(font)
        self.xPosLabel_2.setStyleSheet("")
        self.xPosLabel_2.setObjectName("xPosLabel_2")
        self.xPosLabel_4 = QtWidgets.QLabel(self.tab)
        self.xPosLabel_4.setGeometry(QtCore.QRect(142, 275, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.xPosLabel_4.setFont(font)
        self.xPosLabel_4.setStyleSheet("")
        self.xPosLabel_4.setObjectName("xPosLabel_4")
        self.toolDiameter = QtWidgets.QDoubleSpinBox(self.tab)
        self.toolDiameter.setGeometry(QtCore.QRect(10, 237, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.toolDiameter.setFont(font)
        self.toolDiameter.setStyleSheet("")
        self.toolDiameter.setDecimals(2)
        self.toolDiameter.setMinimum(0.0)
        self.toolDiameter.setMaximum(400.0)
        self.toolDiameter.setSingleStep(0.1)
        self.toolDiameter.setProperty("value", 1.0)
        self.toolDiameter.setObjectName("toolDiameter")
        self.xPosLabel_11 = QtWidgets.QLabel(self.tab)
        self.xPosLabel_11.setGeometry(QtCore.QRect(12, 69, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.xPosLabel_11.setFont(font)
        self.xPosLabel_11.setStyleSheet("")
        self.xPosLabel_11.setObjectName("xPosLabel_11")
        self.scaleSvg = QtWidgets.QDoubleSpinBox(self.tab)
        self.scaleSvg.setGeometry(QtCore.QRect(10, 90, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.scaleSvg.setFont(font)
        self.scaleSvg.setStyleSheet("")
        self.scaleSvg.setDecimals(2)
        self.scaleSvg.setMinimum(0.0)
        self.scaleSvg.setMaximum(400.0)
        self.scaleSvg.setSingleStep(0.1)
        self.scaleSvg.setProperty("value", 1.0)
        self.scaleSvg.setObjectName("scaleSvg")
        self.line_5 = QtWidgets.QFrame(self.tab)
        self.line_5.setGeometry(QtCore.QRect(7, 130, 241, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.generateProgressSvg = QtWidgets.QLabel(self.tab)
        self.generateProgressSvg.setGeometry(QtCore.QRect(40, 500, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.generateProgressSvg.setFont(font)
        self.generateProgressSvg.setObjectName("generateProgressSvg")
        self.svgProcessingStrategy = QtWidgets.QComboBox(self.tab)
        self.svgProcessingStrategy.setGeometry(QtCore.QRect(10, 177, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.svgProcessingStrategy.setFont(font)
        self.svgProcessingStrategy.setObjectName("svgProcessingStrategy")
        self.svgProcessingStrategy.addItem("")
        self.svgProcessingStrategy.addItem("")
        self.xPosLabel_15 = QtWidgets.QLabel(self.tab)
        self.xPosLabel_15.setGeometry(QtCore.QRect(12, 150, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.xPosLabel_15.setFont(font)
        self.xPosLabel_15.setStyleSheet("")
        self.xPosLabel_15.setObjectName("xPosLabel_15")
        self.offsetX = QtWidgets.QDoubleSpinBox(self.tab)
        self.offsetX.setGeometry(QtCore.QRect(10, 357, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.offsetX.setFont(font)
        self.offsetX.setStyleSheet("")
        self.offsetX.setDecimals(2)
        self.offsetX.setMinimum(0.0)
        self.offsetX.setMaximum(100.0)
        self.offsetX.setSingleStep(1.0)
        self.offsetX.setObjectName("offsetX")
        self.offsetY = QtWidgets.QDoubleSpinBox(self.tab)
        self.offsetY.setGeometry(QtCore.QRect(140, 357, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.offsetY.setFont(font)
        self.offsetY.setStyleSheet("")
        self.offsetY.setDecimals(2)
        self.offsetY.setMinimum(0.0)
        self.offsetY.setMaximum(100.0)
        self.offsetY.setSingleStep(1.0)
        self.offsetY.setProperty("value", 0.0)
        self.offsetY.setObjectName("offsetY")
        self.xOffsetLabel = QtWidgets.QLabel(self.tab)
        self.xOffsetLabel.setGeometry(QtCore.QRect(12, 337, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.xOffsetLabel.setFont(font)
        self.xOffsetLabel.setStyleSheet("")
        self.xOffsetLabel.setObjectName("xOffsetLabel")
        self.yOffsetLabel = QtWidgets.QLabel(self.tab)
        self.yOffsetLabel.setGeometry(QtCore.QRect(142, 337, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.yOffsetLabel.setFont(font)
        self.yOffsetLabel.setStyleSheet("")
        self.yOffsetLabel.setObjectName("yOffsetLabel")
        self.nullpunktPosition_SVG = QtWidgets.QComboBox(self.tab)
        self.nullpunktPosition_SVG.setGeometry(QtCore.QRect(130, 91, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.nullpunktPosition_SVG.setFont(font)
        self.nullpunktPosition_SVG.setObjectName("nullpunktPosition_SVG")
        self.nullpunktPosition_SVG.addItem("")
        self.nullpunktPosition_SVG.addItem("")
        self.nullpunktPosition_SVG.addItem("")
        self.xPosLabel_17 = QtWidgets.QLabel(self.tab)
        self.xPosLabel_17.setGeometry(QtCore.QRect(132, 69, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.xPosLabel_17.setFont(font)
        self.xPosLabel_17.setStyleSheet("")
        self.xPosLabel_17.setObjectName("xPosLabel_17")
        self.tabWidget_2.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.stlFilePathLabel = QtWidgets.QLabel(self.tab_4)
        self.stlFilePathLabel.setGeometry(QtCore.QRect(120, 10, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stlFilePathLabel.setFont(font)
        self.stlFilePathLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.stlFilePathLabel.setObjectName("stlFilePathLabel")
        self.stlExportButton = QtWidgets.QPushButton(self.tab_4)
        self.stlExportButton.setGeometry(QtCore.QRect(30, 530, 191, 41))
        self.stlExportButton.setIcon(icon1)
        self.stlExportButton.setObjectName("stlExportButton")
        self.stlImportButton = QtWidgets.QPushButton(self.tab_4)
        self.stlImportButton.setGeometry(QtCore.QRect(10, 10, 113, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.stlImportButton.setFont(font)
        self.stlImportButton.setIcon(icon)
        self.stlImportButton.setObjectName("stlImportButton")
        self.safetyDistanceStl = QtWidgets.QDoubleSpinBox(self.tab_4)
        self.safetyDistanceStl.setGeometry(QtCore.QRect(140, 237, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.safetyDistanceStl.setFont(font)
        self.safetyDistanceStl.setStyleSheet("")
        self.safetyDistanceStl.setDecimals(1)
        self.safetyDistanceStl.setMinimum(0.0)
        self.safetyDistanceStl.setMaximum(400.0)
        self.safetyDistanceStl.setSingleStep(0.1)
        self.safetyDistanceStl.setProperty("value", 5.0)
        self.safetyDistanceStl.setObjectName("safetyDistanceStl")
        self.xPosLabel_6 = QtWidgets.QLabel(self.tab_4)
        self.xPosLabel_6.setGeometry(QtCore.QRect(12, 216, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.xPosLabel_6.setFont(font)
        self.xPosLabel_6.setStyleSheet("")
        self.xPosLabel_6.setObjectName("xPosLabel_6")
        self.toolDiameterStl = QtWidgets.QDoubleSpinBox(self.tab_4)
        self.toolDiameterStl.setGeometry(QtCore.QRect(10, 237, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.toolDiameterStl.setFont(font)
        self.toolDiameterStl.setStyleSheet("")
        self.toolDiameterStl.setDecimals(2)
        self.toolDiameterStl.setMinimum(0.0)
        self.toolDiameterStl.setMaximum(400.0)
        self.toolDiameterStl.setSingleStep(0.1)
        self.toolDiameterStl.setProperty("value", 1.0)
        self.toolDiameterStl.setObjectName("toolDiameterStl")
        self.numberOfLayersStl = QtWidgets.QDoubleSpinBox(self.tab_4)
        self.numberOfLayersStl.setGeometry(QtCore.QRect(140, 296, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.numberOfLayersStl.setFont(font)
        self.numberOfLayersStl.setStyleSheet("")
        self.numberOfLayersStl.setDecimals(0)
        self.numberOfLayersStl.setMinimum(1.0)
        self.numberOfLayersStl.setMaximum(100.0)
        self.numberOfLayersStl.setSingleStep(1.0)
        self.numberOfLayersStl.setObjectName("numberOfLayersStl")
        self.xPosLabel_7 = QtWidgets.QLabel(self.tab_4)
        self.xPosLabel_7.setGeometry(QtCore.QRect(142, 216, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.xPosLabel_7.setFont(font)
        self.xPosLabel_7.setStyleSheet("")
        self.xPosLabel_7.setObjectName("xPosLabel_7")
        self.xPosLabel_8 = QtWidgets.QLabel(self.tab_4)
        self.xPosLabel_8.setGeometry(QtCore.QRect(142, 275, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.xPosLabel_8.setFont(font)
        self.xPosLabel_8.setStyleSheet("")
        self.xPosLabel_8.setObjectName("xPosLabel_8")
        self.generateStlToolpath = QtWidgets.QPushButton(self.tab_4)
        self.generateStlToolpath.setGeometry(QtCore.QRect(30, 460, 191, 41))
        self.generateStlToolpath.setIcon(icon2)
        self.generateStlToolpath.setObjectName("generateStlToolpath")
        self.sliceDistance = QtWidgets.QDoubleSpinBox(self.tab_4)
        self.sliceDistance.setGeometry(QtCore.QRect(10, 296, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.sliceDistance.setFont(font)
        self.sliceDistance.setStyleSheet("")
        self.sliceDistance.setDecimals(2)
        self.sliceDistance.setMinimum(0.0)
        self.sliceDistance.setMaximum(400.0)
        self.sliceDistance.setSingleStep(0.1)
        self.sliceDistance.setProperty("value", 5.0)
        self.sliceDistance.setObjectName("sliceDistance")
        self.xPosLabel_9 = QtWidgets.QLabel(self.tab_4)
        self.xPosLabel_9.setGeometry(QtCore.QRect(12, 275, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.xPosLabel_9.setFont(font)
        self.xPosLabel_9.setStyleSheet("")
        self.xPosLabel_9.setObjectName("xPosLabel_9")
        self.processingStrategy = QtWidgets.QComboBox(self.tab_4)
        self.processingStrategy.setGeometry(QtCore.QRect(10, 177, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.processingStrategy.setFont(font)
        self.processingStrategy.setObjectName("processingStrategy")
        self.processingStrategy.addItem("")
        self.processingStrategy.addItem("")
        self.processingStrategy.addItem("")
        self.xPosLabel_10 = QtWidgets.QLabel(self.tab_4)
        self.xPosLabel_10.setGeometry(QtCore.QRect(12, 150, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.xPosLabel_10.setFont(font)
        self.xPosLabel_10.setStyleSheet("")
        self.xPosLabel_10.setObjectName("xPosLabel_10")
        self.xPosLabel_12 = QtWidgets.QLabel(self.tab_4)
        self.xPosLabel_12.setGeometry(QtCore.QRect(12, 69, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.xPosLabel_12.setFont(font)
        self.xPosLabel_12.setStyleSheet("")
        self.xPosLabel_12.setObjectName("xPosLabel_12")
        self.scaleStl = QtWidgets.QDoubleSpinBox(self.tab_4)
        self.scaleStl.setGeometry(QtCore.QRect(10, 90, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.scaleStl.setFont(font)
        self.scaleStl.setStyleSheet("")
        self.scaleStl.setDecimals(2)
        self.scaleStl.setMinimum(0.0)
        self.scaleStl.setMaximum(400.0)
        self.scaleStl.setSingleStep(0.1)
        self.scaleStl.setProperty("value", 1.0)
        self.scaleStl.setObjectName("scaleStl")
        self.line_6 = QtWidgets.QFrame(self.tab_4)
        self.line_6.setGeometry(QtCore.QRect(10, 131, 241, 20))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.generateProgressStl = QtWidgets.QLabel(self.tab_4)
        self.generateProgressStl.setGeometry(QtCore.QRect(40, 500, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.generateProgressStl.setFont(font)
        self.generateProgressStl.setObjectName("generateProgressStl")
        self.invertContour = QtWidgets.QCheckBox(self.tab_4)
        self.invertContour.setGeometry(QtCore.QRect(140, 170, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.invertContour.setFont(font)
        self.invertContour.setObjectName("invertContour")
        self.nullpunktPosition_STL = QtWidgets.QComboBox(self.tab_4)
        self.nullpunktPosition_STL.setGeometry(QtCore.QRect(130, 91, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.nullpunktPosition_STL.setFont(font)
        self.nullpunktPosition_STL.setObjectName("nullpunktPosition_STL")
        self.nullpunktPosition_STL.addItem("")
        self.nullpunktPosition_STL.addItem("")
        self.nullpunktPosition_STL.addItem("")
        self.xPosLabel_16 = QtWidgets.QLabel(self.tab_4)
        self.xPosLabel_16.setGeometry(QtCore.QRect(132, 69, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.xPosLabel_16.setFont(font)
        self.xPosLabel_16.setStyleSheet("")
        self.xPosLabel_16.setObjectName("xPosLabel_16")
        self.tabWidget_2.addTab(self.tab_4, "")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab_1)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(290, 10, 681, 591))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.plot3d = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.plot3d.setContentsMargins(0, 0, 0, 0)
        self.plot3d.setObjectName("plot3d")
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.line = QtWidgets.QFrame(self.tab_2)
        self.line.setGeometry(QtCore.QRect(280, 0, 20, 601))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 130, 281, 281))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.stopButton = QtWidgets.QPushButton(self.groupBox_2)
        self.stopButton.setGeometry(QtCore.QRect(182, 70, 85, 41))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.stopButton.setFont(font)
        self.stopButton.setStyleSheet("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("GUI/icons//navigation/png/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopButton.setIcon(icon3)
        self.stopButton.setObjectName("stopButton")
        self.runButton = QtWidgets.QPushButton(self.groupBox_2)
        self.runButton.setGeometry(QtCore.QRect(7, 70, 85, 41))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.runButton.setFont(font)
        self.runButton.setStyleSheet("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("GUI/icons//navigation/png/next-1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.runButton.setIcon(icon4)
        self.runButton.setObjectName("runButton")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox_2)
        self.progressBar.setGeometry(QtCore.QRect(10, 220, 211, 51))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(10, 220, 59, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.xPosLabel = QtWidgets.QLabel(self.groupBox_2)
        self.xPosLabel.setGeometry(QtCore.QRect(20, 120, 31, 21))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(14)
        self.xPosLabel.setFont(font)
        self.xPosLabel.setStyleSheet("")
        self.xPosLabel.setObjectName("xPosLabel")
        self.yPosLabel = QtWidgets.QLabel(self.groupBox_2)
        self.yPosLabel.setGeometry(QtCore.QRect(20, 150, 31, 21))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(14)
        self.yPosLabel.setFont(font)
        self.yPosLabel.setStyleSheet("")
        self.yPosLabel.setObjectName("yPosLabel")
        self.zPosLabel = QtWidgets.QLabel(self.groupBox_2)
        self.zPosLabel.setGeometry(QtCore.QRect(20, 180, 31, 21))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(14)
        self.zPosLabel.setFont(font)
        self.zPosLabel.setStyleSheet("")
        self.zPosLabel.setObjectName("zPosLabel")
        self.xPosValue = QtWidgets.QLabel(self.groupBox_2)
        self.xPosValue.setGeometry(QtCore.QRect(60, 120, 131, 21))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(14)
        self.xPosValue.setFont(font)
        self.xPosValue.setStyleSheet("")
        self.xPosValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.xPosValue.setObjectName("xPosValue")
        self.yPosValue = QtWidgets.QLabel(self.groupBox_2)
        self.yPosValue.setGeometry(QtCore.QRect(60, 150, 131, 21))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(14)
        self.yPosValue.setFont(font)
        self.yPosValue.setStyleSheet("")
        self.yPosValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.yPosValue.setObjectName("yPosValue")
        self.zPosValue = QtWidgets.QLabel(self.groupBox_2)
        self.zPosValue.setGeometry(QtCore.QRect(60, 180, 131, 21))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(14)
        self.zPosValue.setFont(font)
        self.zPosValue.setStyleSheet("")
        self.zPosValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.zPosValue.setObjectName("zPosValue")
        self.progressValue = QtWidgets.QLabel(self.groupBox_2)
        self.progressValue.setGeometry(QtCore.QRect(230, 237, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.progressValue.setFont(font)
        self.progressValue.setObjectName("progressValue")
        self.speed = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.speed.setGeometry(QtCore.QRect(160, 30, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.speed.setFont(font)
        self.speed.setStyleSheet("")
        self.speed.setDecimals(1)
        self.speed.setMinimum(0.5)
        self.speed.setMaximum(400.0)
        self.speed.setSingleStep(0.1)
        self.speed.setProperty("value", 1.0)
        self.speed.setObjectName("speed")
        self.xPosLabel_13 = QtWidgets.QLabel(self.groupBox_2)
        self.xPosLabel_13.setGeometry(QtCore.QRect(15, 30, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.xPosLabel_13.setFont(font)
        self.xPosLabel_13.setStyleSheet("")
        self.xPosLabel_13.setObjectName("xPosLabel_13")
        self.pauseButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pauseButton.setGeometry(QtCore.QRect(94, 70, 85, 41))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pauseButton.setFont(font)
        self.pauseButton.setStyleSheet("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("GUI/icons//navigation/png/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pauseButton.setIcon(icon5)
        self.pauseButton.setObjectName("pauseButton")
        self.loadNpz = QtWidgets.QGroupBox(self.tab_2)
        self.loadNpz.setGeometry(QtCore.QRect(0, 20, 281, 81))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.loadNpz.setFont(font)
        self.loadNpz.setObjectName("loadNpz")
        self.loadConvertedFileButton = QtWidgets.QPushButton(self.loadNpz)
        self.loadConvertedFileButton.setGeometry(QtCore.QRect(10, 30, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.loadConvertedFileButton.setFont(font)
        self.loadConvertedFileButton.setStyleSheet("")
        self.loadConvertedFileButton.setIcon(icon)
        self.loadConvertedFileButton.setObjectName("loadConvertedFileButton")
        self.npzImportName = QtWidgets.QLabel(self.loadNpz)
        self.npzImportName.setGeometry(QtCore.QRect(100, 35, 171, 31))
        self.npzImportName.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.npzImportName.setObjectName("npzImportName")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 480, 281, 121))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setGeometry(QtCore.QRect(10, 30, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setGeometry(QtCore.QRect(10, 60, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setGeometry(QtCore.QRect(10, 90, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.endswitchYRear1 = QtWidgets.QFrame(self.groupBox_4)
        self.endswitchYRear1.setGeometry(QtCore.QRect(70, 60, 20, 20))
        self.endswitchYRear1.setStyleSheet("QWidget { background: qradialgradient(cx: 0.5, cy: 0.5,\n"
"fx: 0.5, fy: 0.5,\n"
"radius: 1, stop: 0 #e1ff00, stop: 1 #7ae500);\n"
"border-radius: 10px;border: 2px solid rgb(183, 186, 186);}")
        self.endswitchYRear1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.endswitchYRear1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.endswitchYRear1.setObjectName("endswitchYRear1")
        self.endswitchYFront2 = QtWidgets.QFrame(self.groupBox_4)
        self.endswitchYFront2.setGeometry(QtCore.QRect(110, 60, 20, 20))
        self.endswitchYFront2.setStyleSheet("QWidget { background: qradialgradient(cx: 0.5, cy: 0.5,\n"
"fx: 0.5, fy: 0.5,\n"
"radius: 1, stop: 0 #e1ff00, stop: 1 #7ae500);\n"
"border-radius: 10px;border: 2px solid rgb(183, 186, 186);}")
        self.endswitchYFront2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.endswitchYFront2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.endswitchYFront2.setObjectName("endswitchYFront2")
        self.endswitchYRear2 = QtWidgets.QFrame(self.groupBox_4)
        self.endswitchYRear2.setGeometry(QtCore.QRect(140, 60, 20, 20))
        self.endswitchYRear2.setStyleSheet("QWidget { background: qradialgradient(cx: 0.5, cy: 0.5,\n"
"fx: 0.5, fy: 0.5,\n"
"radius: 1, stop: 0 #e1ff00, stop: 1 #7ae500);\n"
"border-radius: 10px;border: 2px solid rgb(183, 186, 186);}")
        self.endswitchYRear2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.endswitchYRear2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.endswitchYRear2.setObjectName("endswitchYRear2")
        self.endswitchXRear = QtWidgets.QFrame(self.groupBox_4)
        self.endswitchXRear.setGeometry(QtCore.QRect(70, 30, 20, 20))
        self.endswitchXRear.setStyleSheet("QWidget { background: qradialgradient(cx: 0.5, cy: 0.5,\n"
"fx: 0.5, fy: 0.5,\n"
"radius: 1, stop: 0 #e1ff00, stop: 1 #7ae500);\n"
"border-radius: 10px;border: 2px solid rgb(183, 186, 186);}")
        self.endswitchXRear.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.endswitchXRear.setFrameShadow(QtWidgets.QFrame.Raised)
        self.endswitchXRear.setObjectName("endswitchXRear")
        self.endswitchZFront = QtWidgets.QFrame(self.groupBox_4)
        self.endswitchZFront.setGeometry(QtCore.QRect(40, 90, 20, 20))
        self.endswitchZFront.setStyleSheet("QWidget { background: qradialgradient(cx: 0.5, cy: 0.5,\n"
"fx: 0.5, fy: 0.5,\n"
"radius: 1, stop: 0 #e1ff00, stop: 1 #7ae500);\n"
"border-radius: 10px;border: 2px solid rgb(183, 186, 186);}")
        self.endswitchZFront.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.endswitchZFront.setFrameShadow(QtWidgets.QFrame.Raised)
        self.endswitchZFront.setObjectName("endswitchZFront")
        self.endswitchZRear = QtWidgets.QFrame(self.groupBox_4)
        self.endswitchZRear.setGeometry(QtCore.QRect(70, 90, 20, 20))
        self.endswitchZRear.setStyleSheet("QWidget { background: qradialgradient(cx: 0.5, cy: 0.5,\n"
"fx: 0.5, fy: 0.5,\n"
"radius: 1, stop: 0 #e1ff00, stop: 1 #7ae500);\n"
"border-radius: 10px;border: 2px solid rgb(183, 186, 186);}")
        self.endswitchZRear.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.endswitchZRear.setFrameShadow(QtWidgets.QFrame.Raised)
        self.endswitchZRear.setObjectName("endswitchZRear")
        self.endswitchYFront1 = QtWidgets.QFrame(self.groupBox_4)
        self.endswitchYFront1.setGeometry(QtCore.QRect(40, 60, 21, 21))
        self.endswitchYFront1.setStyleSheet("QWidget { background: qradialgradient(cx: 0.5, cy: 0.5,\n"
"fx: 0.5, fy: 0.5,\n"
"radius: 1, stop: 0 #e1ff00, stop: 1 #7ae500);\n"
"border-radius: 10px;border: 2px solid rgb(183, 186, 186);}")
        self.endswitchYFront1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.endswitchYFront1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.endswitchYFront1.setObjectName("endswitchYFront1")
        self.endswitchXFront = QtWidgets.QFrame(self.groupBox_4)
        self.endswitchXFront.setGeometry(QtCore.QRect(40, 30, 20, 20))
        self.endswitchXFront.setStyleSheet("QWidget { background: qradialgradient(cx: 0.5, cy: 0.5,\n"
"fx: 0.5, fy: 0.5,\n"
"radius: 1, stop: 0 #e1ff00, stop: 1 #7ae500);\n"
"border-radius: 10px;border: 2px solid rgb(183, 186, 186);}")
        self.endswitchXFront.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.endswitchXFront.setFrameShadow(QtWidgets.QFrame.Raised)
        self.endswitchXFront.setObjectName("endswitchXFront")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(290, 10, 681, 591))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.plot3dProgramCode = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.plot3dProgramCode.setContentsMargins(0, 0, 0, 0)
        self.plot3dProgramCode.setObjectName("plot3dProgramCode")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setEnabled(True)
        self.tab_3.setObjectName("tab_3")
        self.joggPosXSlow = QtWidgets.QPushButton(self.tab_3)
        self.joggPosXSlow.setGeometry(QtCore.QRect(667, 280, 50, 50))
        self.joggPosXSlow.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("GUI/icons//arrows/png/right-arrow-5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.joggPosXSlow.setIcon(icon6)
        self.joggPosXSlow.setIconSize(QtCore.QSize(30, 30))
        self.joggPosXSlow.setObjectName("joggPosXSlow")
        self.joggPosYSlow = QtWidgets.QPushButton(self.tab_3)
        self.joggPosYSlow.setGeometry(QtCore.QRect(618, 229, 50, 50))
        self.joggPosYSlow.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("GUI/icons//arrows/png/up-arrow-4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.joggPosYSlow.setIcon(icon7)
        self.joggPosYSlow.setIconSize(QtCore.QSize(30, 30))
        self.joggPosYSlow.setObjectName("joggPosYSlow")
        self.joggNegXSlow = QtWidgets.QPushButton(self.tab_3)
        self.joggNegXSlow.setGeometry(QtCore.QRect(570, 280, 50, 50))
        self.joggNegXSlow.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("GUI/icons//arrows/png/left-arrow-4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.joggNegXSlow.setIcon(icon8)
        self.joggNegXSlow.setIconSize(QtCore.QSize(30, 30))
        self.joggNegXSlow.setObjectName("joggNegXSlow")
        self.joggNegYSlow = QtWidgets.QPushButton(self.tab_3)
        self.joggNegYSlow.setGeometry(QtCore.QRect(618, 332, 50, 50))
        self.joggNegYSlow.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("GUI/icons//arrows/png/down-arrow-4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.joggNegYSlow.setIcon(icon9)
        self.joggNegYSlow.setIconSize(QtCore.QSize(30, 30))
        self.joggNegYSlow.setObjectName("joggNegYSlow")
        self.joggPosYFast = QtWidgets.QPushButton(self.tab_3)
        self.joggPosYFast.setGeometry(QtCore.QRect(618, 173, 50, 50))
        self.joggPosYFast.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("GUI/icons//arrows/png/chevron-1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.joggPosYFast.setIcon(icon10)
        self.joggPosYFast.setIconSize(QtCore.QSize(30, 30))
        self.joggPosYFast.setObjectName("joggPosYFast")
        self.joggPosXFast = QtWidgets.QPushButton(self.tab_3)
        self.joggPosXFast.setGeometry(QtCore.QRect(718, 280, 50, 50))
        self.joggPosXFast.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("GUI/icons//arrows/png/chevron-3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.joggPosXFast.setIcon(icon11)
        self.joggPosXFast.setIconSize(QtCore.QSize(30, 30))
        self.joggPosXFast.setObjectName("joggPosXFast")
        self.joggNegYFast = QtWidgets.QPushButton(self.tab_3)
        self.joggNegYFast.setGeometry(QtCore.QRect(618, 387, 50, 50))
        self.joggNegYFast.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("GUI/icons//arrows/png/chevron.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.joggNegYFast.setIcon(icon12)
        self.joggNegYFast.setIconSize(QtCore.QSize(30, 30))
        self.joggNegYFast.setObjectName("joggNegYFast")
        self.joggNegXFast = QtWidgets.QPushButton(self.tab_3)
        self.joggNegXFast.setGeometry(QtCore.QRect(519, 280, 50, 50))
        self.joggNegXFast.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("GUI/icons//arrows/png/chevron-2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.joggNegXFast.setIcon(icon13)
        self.joggNegXFast.setIconSize(QtCore.QSize(30, 30))
        self.joggNegXFast.setObjectName("joggNegXFast")
        self.line_3 = QtWidgets.QFrame(self.tab_3)
        self.line_3.setGeometry(QtCore.QRect(360, 0, 20, 601))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.xSetPoint = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.xSetPoint.setGeometry(QtCore.QRect(70, 80, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.xSetPoint.setFont(font)
        self.xSetPoint.setStyleSheet("")
        self.xSetPoint.setMinimum(-400.0)
        self.xSetPoint.setMaximum(400.0)
        self.xSetPoint.setSingleStep(0.05)
        self.xSetPoint.setObjectName("xSetPoint")
        self.ySetPoint = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.ySetPoint.setGeometry(QtCore.QRect(70, 130, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ySetPoint.setFont(font)
        self.ySetPoint.setStyleSheet("")
        self.ySetPoint.setMinimum(-400.0)
        self.ySetPoint.setMaximum(400.0)
        self.ySetPoint.setSingleStep(0.05)
        self.ySetPoint.setObjectName("ySetPoint")
        self.zSetPoint = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.zSetPoint.setGeometry(QtCore.QRect(70, 180, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.zSetPoint.setFont(font)
        self.zSetPoint.setStyleSheet("")
        self.zSetPoint.setMinimum(-150.0)
        self.zSetPoint.setMaximum(150.0)
        self.zSetPoint.setSingleStep(0.05)
        self.zSetPoint.setObjectName("zSetPoint")
        self.xPosLabelMove = QtWidgets.QLabel(self.tab_3)
        self.xPosLabelMove.setGeometry(QtCore.QRect(40, 90, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.xPosLabelMove.setFont(font)
        self.xPosLabelMove.setStyleSheet("")
        self.xPosLabelMove.setObjectName("xPosLabelMove")
        self.yPosLabelMove = QtWidgets.QLabel(self.tab_3)
        self.yPosLabelMove.setGeometry(QtCore.QRect(40, 140, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.yPosLabelMove.setFont(font)
        self.yPosLabelMove.setStyleSheet("")
        self.yPosLabelMove.setObjectName("yPosLabelMove")
        self.zPosLabelMove = QtWidgets.QLabel(self.tab_3)
        self.zPosLabelMove.setGeometry(QtCore.QRect(40, 190, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.zPosLabelMove.setFont(font)
        self.zPosLabelMove.setStyleSheet("")
        self.zPosLabelMove.setObjectName("zPosLabelMove")
        self.label_12 = QtWidgets.QLabel(self.tab_3)
        self.label_12.setGeometry(QtCore.QRect(70, 40, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setGeometry(QtCore.QRect(190, 40, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("")
        self.label_13.setObjectName("label_13")
        self.currentXpos = QtWidgets.QLabel(self.tab_3)
        self.currentXpos.setGeometry(QtCore.QRect(170, 86, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.currentXpos.setFont(font)
        self.currentXpos.setStyleSheet("")
        self.currentXpos.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.currentXpos.setObjectName("currentXpos")
        self.currentYpos = QtWidgets.QLabel(self.tab_3)
        self.currentYpos.setGeometry(QtCore.QRect(170, 135, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.currentYpos.setFont(font)
        self.currentYpos.setStyleSheet("")
        self.currentYpos.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.currentYpos.setObjectName("currentYpos")
        self.currentZpos = QtWidgets.QLabel(self.tab_3)
        self.currentZpos.setGeometry(QtCore.QRect(170, 180, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.currentZpos.setFont(font)
        self.currentZpos.setStyleSheet("")
        self.currentZpos.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.currentZpos.setObjectName("currentZpos")
        self.goToPosition = QtWidgets.QPushButton(self.tab_3)
        self.goToPosition.setGeometry(QtCore.QRect(60, 280, 111, 41))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.goToPosition.setFont(font)
        self.goToPosition.setStyleSheet("")
        self.goToPosition.setIcon(icon4)
        self.goToPosition.setIconSize(QtCore.QSize(20, 20))
        self.goToPosition.setObjectName("goToPosition")
        self.goHome = QtWidgets.QPushButton(self.tab_3)
        self.goHome.setGeometry(QtCore.QRect(20, 430, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.goHome.setFont(font)
        self.goHome.setStyleSheet("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("GUI/icons//navigation/png/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.goHome.setIcon(icon14)
        self.goHome.setIconSize(QtCore.QSize(20, 20))
        self.goHome.setObjectName("goHome")
        self.setHome = QtWidgets.QPushButton(self.tab_3)
        self.setHome.setGeometry(QtCore.QRect(20, 480, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.setHome.setFont(font)
        self.setHome.setStyleSheet("")
        self.setHome.setIcon(icon14)
        self.setHome.setIconSize(QtCore.QSize(20, 20))
        self.setHome.setObjectName("setHome")
        self.stopManualDrive = QtWidgets.QPushButton(self.tab_3)
        self.stopManualDrive.setGeometry(QtCore.QRect(200, 280, 111, 41))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.stopManualDrive.setFont(font)
        self.stopManualDrive.setStyleSheet("")
        self.stopManualDrive.setIcon(icon3)
        self.stopManualDrive.setIconSize(QtCore.QSize(20, 20))
        self.stopManualDrive.setObjectName("stopManualDrive")
        self.line_4 = QtWidgets.QFrame(self.tab_3)
        self.line_4.setGeometry(QtCore.QRect(10, 370, 331, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.joggPosZFast = QtWidgets.QPushButton(self.tab_3)
        self.joggPosZFast.setGeometry(QtCore.QRect(798, 190, 50, 50))
        self.joggPosZFast.setText("")
        self.joggPosZFast.setIcon(icon10)
        self.joggPosZFast.setIconSize(QtCore.QSize(30, 30))
        self.joggPosZFast.setObjectName("joggPosZFast")
        self.joggPosZSlow = QtWidgets.QPushButton(self.tab_3)
        self.joggPosZSlow.setGeometry(QtCore.QRect(798, 245, 50, 50))
        self.joggPosZSlow.setText("")
        self.joggPosZSlow.setIcon(icon7)
        self.joggPosZSlow.setIconSize(QtCore.QSize(30, 30))
        self.joggPosZSlow.setObjectName("joggPosZSlow")
        self.joggNegZSlow = QtWidgets.QPushButton(self.tab_3)
        self.joggNegZSlow.setGeometry(QtCore.QRect(798, 315, 50, 50))
        self.joggNegZSlow.setText("")
        self.joggNegZSlow.setIcon(icon9)
        self.joggNegZSlow.setIconSize(QtCore.QSize(30, 30))
        self.joggNegZSlow.setObjectName("joggNegZSlow")
        self.joggNegZFast = QtWidgets.QPushButton(self.tab_3)
        self.joggNegZFast.setGeometry(QtCore.QRect(798, 370, 50, 50))
        self.joggNegZFast.setText("")
        self.joggNegZFast.setIcon(icon12)
        self.joggNegZFast.setIconSize(QtCore.QSize(30, 30))
        self.joggNegZFast.setObjectName("joggNegZFast")
        self.setZero = QtWidgets.QPushButton(self.tab_3)
        self.setZero.setGeometry(QtCore.QRect(20, 530, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.setZero.setFont(font)
        self.setZero.setStyleSheet("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("GUI/icons//navigation/png/placeholder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setZero.setIcon(icon15)
        self.setZero.setIconSize(QtCore.QSize(20, 20))
        self.setZero.setObjectName("setZero")
        self.label_14 = QtWidgets.QLabel(self.tab_3)
        self.label_14.setGeometry(QtCore.QRect(498, 295, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab_3)
        self.label_15.setGeometry(QtCore.QRect(641, 140, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.tab_3)
        self.label_16.setGeometry(QtCore.QRect(820, 160, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("")
        self.label_16.setObjectName("label_16")
        self.performReferenceScan = QtWidgets.QPushButton(self.tab_3)
        self.performReferenceScan.setGeometry(QtCore.QRect(190, 430, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.performReferenceScan.setFont(font)
        self.performReferenceScan.setStyleSheet("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("GUI/icons//navigation/png/controller.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.performReferenceScan.setIcon(icon16)
        self.performReferenceScan.setIconSize(QtCore.QSize(20, 20))
        self.performReferenceScan.setObjectName("performReferenceScan")
        self.xPosLabel_14 = QtWidgets.QLabel(self.tab_3)
        self.xPosLabel_14.setGeometry(QtCore.QRect(70, 230, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.xPosLabel_14.setFont(font)
        self.xPosLabel_14.setStyleSheet("")
        self.xPosLabel_14.setObjectName("xPosLabel_14")
        self.speedManualDrive = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.speedManualDrive.setGeometry(QtCore.QRect(210, 230, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.speedManualDrive.setFont(font)
        self.speedManualDrive.setStyleSheet("")
        self.speedManualDrive.setDecimals(1)
        self.speedManualDrive.setMinimum(0.5)
        self.speedManualDrive.setMaximum(400.0)
        self.speedManualDrive.setSingleStep(0.1)
        self.speedManualDrive.setProperty("value", 1.0)
        self.speedManualDrive.setObjectName("speedManualDrive")
        self.label_17 = QtWidgets.QLabel(self.tab_3)
        self.label_17.setGeometry(QtCore.QRect(200, 500, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("")
        self.label_17.setObjectName("label_17")
        self.toggleMillingMotor = QtWidgets.QSlider(self.tab_3)
        self.toggleMillingMotor.setEnabled(True)
        self.toggleMillingMotor.setGeometry(QtCore.QRect(200, 537, 51, 22))
        self.toggleMillingMotor.setMaximum(1)
        self.toggleMillingMotor.setPageStep(1)
        self.toggleMillingMotor.setTracking(True)
        self.toggleMillingMotor.setOrientation(QtCore.Qt.Horizontal)
        self.toggleMillingMotor.setInvertedAppearance(False)
        self.toggleMillingMotor.setInvertedControls(False)
        self.toggleMillingMotor.setObjectName("toggleMillingMotor")
        self.millingMotorLable = QtWidgets.QLabel(self.tab_3)
        self.millingMotorLable.setGeometry(QtCore.QRect(260, 530, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.millingMotorLable.setFont(font)
        self.millingMotorLable.setStyleSheet("")
        self.millingMotorLable.setObjectName("millingMotorLable")
        self.tabWidget.addTab(self.tab_3, "")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(850, 570, 130, 63))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("PiCNiC.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.svgFilePathLabel.setText(_translate("MainWindow", "no file selected"))
        self.svgImportButton.setText(_translate("MainWindow", " Import"))
        self.svgExportButton.setText(_translate("MainWindow", " Export to *.npz      "))
        self.generateSvgToolpath.setText(_translate("MainWindow", " Generate Toolpath"))
        self.xPosLabel_3.setText(_translate("MainWindow", "Safety Dist."))
        self.xPosLabel_5.setText(_translate("MainWindow", "Z depth"))
        self.xPosLabel_2.setText(_translate("MainWindow", "Tool Diam."))
        self.xPosLabel_4.setText(_translate("MainWindow", "Layers"))
        self.xPosLabel_11.setText(_translate("MainWindow", "Scale"))
        self.generateProgressSvg.setText(_translate("MainWindow", "..."))
        self.svgProcessingStrategy.setItemText(0, _translate("MainWindow", "contour"))
        self.svgProcessingStrategy.setItemText(1, _translate("MainWindow", "constant z"))
        self.xPosLabel_15.setText(_translate("MainWindow", "Strategy"))
        self.xOffsetLabel.setText(_translate("MainWindow", "Offset X"))
        self.yOffsetLabel.setText(_translate("MainWindow", "Offset Y"))
        self.nullpunktPosition_SVG.setItemText(0, _translate("MainWindow", "Centered"))
        self.nullpunktPosition_SVG.setItemText(1, _translate("MainWindow", "Bottom Left"))
        self.nullpunktPosition_SVG.setItemText(2, _translate("MainWindow", "Original"))
        self.xPosLabel_17.setText(_translate("MainWindow", "Nullpunkt"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("MainWindow", "svg"))
        self.stlFilePathLabel.setText(_translate("MainWindow", "no file selected"))
        self.stlExportButton.setText(_translate("MainWindow", " Export to *.npz       "))
        self.stlImportButton.setText(_translate("MainWindow", " Import"))
        self.xPosLabel_6.setText(_translate("MainWindow", "Tool Diam."))
        self.xPosLabel_7.setText(_translate("MainWindow", "Safety Dist."))
        self.xPosLabel_8.setText(_translate("MainWindow", "Layers"))
        self.generateStlToolpath.setText(_translate("MainWindow", " Generate Toolpath"))
        self.xPosLabel_9.setText(_translate("MainWindow", "Slice Dist."))
        self.processingStrategy.setItemText(0, _translate("MainWindow", "line"))
        self.processingStrategy.setItemText(1, _translate("MainWindow", "contour"))
        self.processingStrategy.setItemText(2, _translate("MainWindow", "constant z"))
        self.xPosLabel_10.setText(_translate("MainWindow", "Strategy"))
        self.xPosLabel_12.setText(_translate("MainWindow", "Scale"))
        self.generateProgressStl.setText(_translate("MainWindow", "..."))
        self.invertContour.setText(_translate("MainWindow", "Invert\n"
"contour"))
        self.nullpunktPosition_STL.setItemText(0, _translate("MainWindow", "Centered"))
        self.nullpunktPosition_STL.setItemText(1, _translate("MainWindow", "Bottom Left"))
        self.nullpunktPosition_STL.setItemText(2, _translate("MainWindow", "Original"))
        self.xPosLabel_16.setText(_translate("MainWindow", "Nullpunkt"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "stl"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Convert"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Program control"))
        self.stopButton.setText(_translate("MainWindow", " Stop"))
        self.runButton.setText(_translate("MainWindow", " Run   "))
        self.label_9.setText(_translate("MainWindow", "Progress"))
        self.xPosLabel.setText(_translate("MainWindow", "X="))
        self.yPosLabel.setText(_translate("MainWindow", "Y="))
        self.zPosLabel.setText(_translate("MainWindow", "Z="))
        self.xPosValue.setText(_translate("MainWindow", "0.00 mm"))
        self.yPosValue.setText(_translate("MainWindow", "0.00 mm"))
        self.zPosValue.setText(_translate("MainWindow", "0.00 mm"))
        self.progressValue.setText(_translate("MainWindow", "100.0%"))
        self.xPosLabel_13.setText(_translate("MainWindow", "Speed (mm/s)"))
        self.pauseButton.setText(_translate("MainWindow", " Pause"))
        self.loadNpz.setTitle(_translate("MainWindow", "Load *.npz file"))
        self.loadConvertedFileButton.setText(_translate("MainWindow", " Load"))
        self.npzImportName.setText(_translate("MainWindow", "no file selected"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Endswitches"))
        self.label_6.setText(_translate("MainWindow", "X"))
        self.label_7.setText(_translate("MainWindow", "Y"))
        self.label_8.setText(_translate("MainWindow", "Z"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Run"))
        self.xPosLabelMove.setText(_translate("MainWindow", "X"))
        self.yPosLabelMove.setText(_translate("MainWindow", "Y"))
        self.zPosLabelMove.setText(_translate("MainWindow", "Z"))
        self.label_12.setText(_translate("MainWindow", "Setpoint"))
        self.label_13.setText(_translate("MainWindow", "Current value"))
        self.currentXpos.setText(_translate("MainWindow", "0.00 mm"))
        self.currentYpos.setText(_translate("MainWindow", "0.00 mm"))
        self.currentZpos.setText(_translate("MainWindow", "0.00 mm"))
        self.goToPosition.setText(_translate("MainWindow", " Go    "))
        self.goHome.setText(_translate("MainWindow", " Go Home "))
        self.setHome.setText(_translate("MainWindow", " Set Home"))
        self.stopManualDrive.setText(_translate("MainWindow", " Stop"))
        self.setZero.setText(_translate("MainWindow", " Set Zero   "))
        self.label_14.setText(_translate("MainWindow", "X"))
        self.label_15.setText(_translate("MainWindow", "Y"))
        self.label_16.setText(_translate("MainWindow", "Z"))
        self.performReferenceScan.setText(_translate("MainWindow", " Reference"))
        self.xPosLabel_14.setText(_translate("MainWindow", "Speed (mm/s)"))
        self.label_17.setText(_translate("MainWindow", "Milling motor"))
        self.millingMotorLable.setText(_translate("MainWindow", "off"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Move"))
